# Generated by Django 4.2.7 on 2023-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_Category', models.CharField(max_length=100)),
                ('suit_Model', models.CharField(max_length=200)),
                ('suit_Qty', models.IntegerField()),
                ('suit_Gazana', models.IntegerField()),
                ('suit_Price', models.IntegerField()),
                ('suit_Shop', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
