# Generated by Django 4.2.7 on 2023-12-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_user_model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suits_model',
            new_name='Thaans_model',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Category',
            new_name='Thaan_Category',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Gazana',
            new_name='Thaan_Gazana',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Model',
            new_name='Thaan_Model',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Price_Per_Meter',
            new_name='Thaan_Price_Per_Meter',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Qty',
            new_name='Thaan_Qty',
        ),
        migrations.RenameField(
            model_name='thaans_model',
            old_name='Suit_Shop_No',
            new_name='Thaan_Shop_No',
        ),
    ]
