# Generated by Django 4.2.7 on 2024-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_suits_model_thaans_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=500)),
                ('client_ph', models.CharField(max_length=15)),
                ('client_balance', models.IntegerField()),
            ],
        ),
    ]
