# Generated by Django 4.2.7 on 2024-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_client_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_model',
            name='client_city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
    ]
