# Generated by Django 4.2.7 on 2024-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_client_model_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_model',
            name='client_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client_model',
            name='client_city',
            field=models.CharField(max_length=100),
        ),
    ]
