# Generated by Django 4.2.7 on 2024-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_client_model_client_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_ph', models.CharField(max_length=15)),
                ('client_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
