# Generated by Django 4.2.7 on 2024-02-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_billing_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_model',
            name='client_ph',
        ),
        migrations.AlterField(
            model_name='billing_model',
            name='client_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing_model',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client_model'),
        ),
    ]
