# Generated by Django 4.2.7 on 2024-02-01 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_billing_model_client_ph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_model',
            old_name='client_name',
            new_name='client_cnic',
        ),
        migrations.AddField(
            model_name='client_model',
            name='client_cnic',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
