# Generated by Django 4.2.7 on 2024-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_client_name_billing_model_client_cnic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_model',
            name='client_balance',
        ),
        migrations.RemoveField(
            model_name='billing_model',
            name='client_cnic',
        ),
    ]
