# Generated by Django 4.2.7 on 2024-02-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_billing_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_cnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client_model')),
            ],
        ),
    ]
