# Generated by Django 4.2.7 on 2024-02-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_billing_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_model',
            name='client_balance',
        ),
    ]
