# Generated by Django 4.2.7 on 2024-02-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_billing_model_client_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_model',
            old_name='client_cnic',
            new_name='client_name',
        ),
    ]
