# Generated by Django 4.2.7 on 2024-02-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_client_cnic_billing_model_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='billing_model',
            old_name='client_name',
            new_name='client',
        ),
        migrations.AddField(
            model_name='billing_model',
            name='quantity_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_model',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_model',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.stock'),
            preserve_default=False,
        ),
    ]
