# Generated by Django 4.2.7 on 2024-02-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_stock_rename_client_name_billing_model_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_model',
            old_name='client',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='billing_model',
            name='quantity_purchased',
        ),
        migrations.RemoveField(
            model_name='billing_model',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='billing_model',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.thaans_model'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
