# Generated by Django 4.2.7 on 2024-02-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_client_billing_model_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_model',
            name='stock',
        ),
        migrations.AddField(
            model_name='billing_model',
            name='client_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billing_model',
            name='client_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='billing_model',
            name='client_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing_model',
            name='client_cnic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billing_model',
            name='client_ph',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billing_model',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
