# Generated by Django 4.2.7 on 2024-02-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_client_model_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_model',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client_model'),
        ),
    ]
