# Generated by Django 4.2.7 on 2024-02-01 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_billing_model_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_model',
            name='client_cnic',
        ),
        migrations.AlterField(
            model_name='billing_model',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client_model',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thaans_model',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
