# Generated by Django 4.2.7 on 2024-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_client_model_client_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
