# Generated by Django 4.2.7 on 2024-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_billing_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_model',
            name='client_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thaans_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
