# Generated by Django 4.2.7 on 2024-02-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client_model')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
