# Generated by Django 4.2.7 on 2024-02-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_billing_test_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='billing_test',
            new_name='billing_testm',
        ),
    ]
