# Generated by Django 4.2.7 on 2024-02-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_rename_billing_test_billing_testm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='billing_testm',
        ),
    ]
