# Generated by Django 4.2.7 on 2024-02-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='product',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='billing_model',
        ),
        migrations.DeleteModel(
            name='billtest',
        ),
    ]
