# Generated by Django 4.2.7 on 2023-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suits_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suit_Category', models.CharField(max_length=100)),
                ('Suit_Model', models.CharField(max_length=200)),
                ('Suit_Qty', models.IntegerField()),
                ('Suit_Gazana', models.IntegerField()),
                ('Suit_Price_Per_Meter', models.IntegerField()),
                ('Suit_Shop_No', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='suits',
        ),
    ]
