# Generated by Django 4.2.7 on 2023-11-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_suits_model_delete_suits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_model',
        ),
        migrations.RenameField(
            model_name='user_model',
            old_name='name',
            new_name='username',
        ),
    ]
